=== nefarium/nefarium/src/nefarium/server/assets/flow_json_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://regulad.xyz/nefarium/src/nefarium/server/assets/flow_json_schema.json",
    "description": "a Nefarious Authorization Flow",
    "type": "object",
    "title": "Nefarious Authorization Flow",
    "required": [
        "name",
        "redirect_uri_domains",
        "proxy_target",
        "filter_response"
    ],
    "definitions": {
        "authFlow": {
            "type": ["object", "null"],
            "title": "auth_goals",
            "required": [
                "goal_urls",
                "return_body_requires_type",
                "return_body_requires_json_schema",
                "return_body_requires_regex",
                "required_cookies",
                "required_cookies_regex",
                "required_headers",
                "required_headers_regex",
                "required_query_params",
                "required_query_params_regex",
                "status_codes"
            ],
            "properties": {
                "goal_urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "minItems": 0
                },
                "return_body_requires_type": {
                    "type": ["string", "null"]
                },
                "return_body_requires_json_schema": {
                    "type": ["string","object", "null"]
                },
                "return_body_requires_regex": {
                    "type": ["string", "null"]
                },
                "required_cookies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "minItems": 0
                },
                "required_cookies_regex": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "required_headers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "minItems": 0
                },
                "required_headers_regex": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "required_query_params": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "minItems": 0
                },
                "required_query_params_regex": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status_codes": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "minItems": 0
                }
            }
        }
    },
    "properties": {
        "name": {
            "type": "string",
            "description": "The name of the flow. This is used to identify the flow in the end user."
        },
        "description": {
            "type": "string",
            "description": "A description of the flow. This is used to identify the flow in the end user."
        },
        "redirect_uri_domains": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "description": "A list of domains that are allowed to be used as the redirect_uri in the OAuth2 flow. Use * to allow all URIs or use *.example.com to allow all subdomains."
        },
        "proxy_target": {
            "type": "string",
            "description": "The target URL that the proxy will forward requests to."
        },
        "auth_goals": {
            "$ref": "#/definitions/authFlow",
            "description": "The auth goals that the flow will attempt to satisfy and return to the redirect URI."
        },
        "request_proxy": {
            "type": ["string", "null"],
            "description": "The proxy that will be used to make requests to the proxy_target and other possible pages. SOCKS4/5, HTTP, and HTTPS proxies are compatible. Inline authentication."
        },
        "filter_response": {
            "type": "boolean",
            "description": "If true, the proxy will filter the response body to use corrected URLs that keep the user in the proxy."
        },
        "redirect_code": {
            "type": "boolean",
            "description": "If the user should be presented with a code instead of redirected back to the redirect URI. Useful for desktop and non-web applications."
        }
    }
}

=== nefarium/nefarium/examples/flows/twitter.json
{
    "auth_goals": {
        "goal_urls": ["https://api.twitter.com/1.1/onboarding/task.json"],
        "return_body_requires_type": null,
        "return_body_requires_json_schema": null,
        "return_body_requires_regex": null,
        "required_cookies": ["auth_token", "twid", "att", "kdt"],
        "required_cookies_regex": {},
        "required_headers": [],
        "required_headers_regex": {},
        "required_query_params": [],
        "required_query_params_regex": {},
        "status_codes": []
    },
    "description": "Twitter Login",
    "filter_response": true,
    "name": "Twitter",
    "proxy_target": "https://twitter.com/i/flow/login",
    "redirect_uri_domains": ["*"],
    "redirect_code": true,
    "request_proxy": null
}
